server:
  port: 3000
  content: content
  https: false
  httpsPort: 8080
  sslKey: sslcert/server.key
  sslCert: sslcert/server.cert
  showFolder: false # not implemented yet.

wrapper:
  - type: "file"
    src: "*.html"
    dest: "/Users/btang/Workspace/a $path $root"